"""empty message

Revision ID: 4bcca7b679ed
Revises: 
Create Date: 2020-09-07 14:51:04.922329

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4bcca7b679ed'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shows')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shows',
    sa.Column('actors_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('movies_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['actors_id'], ['actors.id'], name='shows_actors_id_fkey'),
    sa.ForeignKeyConstraint(['movies_id'], ['movies.id'], name='shows_movies_id_fkey')
    )
    # ### end Alembic commands ###
